/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdminRole;

import Business.EcoSystem;
import Business.Restaurant.Restaurant;
import Business.menu.Menu;
import Business.menu.MenuDirectory;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lokesh Balaji
 */
public class Addmenupanel extends javax.swing.JPanel {

    /**
     * Creates new form Addmenupanel
     */
    JPanel userProcessContainer;
    EcoSystem system;
    String restaurantName;

    public Addmenupanel(JPanel userProcessContainer, EcoSystem system, String restaurantName) {
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.restaurantName = restaurantName;
        initComponents();
        populatetable();
    }

   
     public void populatetable(){
        DefaultTableModel defaultmenutble = (DefaultTableModel) menutable.getModel();
        defaultmenutble.setRowCount(0);
        
         System.out.println("Menu "+ system.getRestaurantDirectory().getRestaurantList().size());
         Restaurant ro1 = system.getRestaurantDirectory().findRestaurant(restaurantName);
         
        if(ro1.getMd()!=null){
            for(Menu m : ro1.getMd().getMenu()) {
                Object row[] = new Object[3];
                row[0] = m.getItemName();
                row[1] = m.getItemPrice();

                defaultmenutble.addRow(row);
            }
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbhotelname = new javax.swing.JLabel();
        lbmenuitems = new javax.swing.JLabel();
        lbItemPrice = new javax.swing.JLabel();
        menuitemtxt = new javax.swing.JTextField();
        itempricetxt = new javax.swing.JTextField();
        btaddmenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        menutable = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Menu");

        lbhotelname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbhotelname.setText("Hotelname");

        lbmenuitems.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbmenuitems.setText("Menu Items");

        lbItemPrice.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbItemPrice.setText("Item Price");

        btaddmenu.setText("Add Menu");
        btaddmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddmenuActionPerformed(evt);
            }
        });

        menutable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Item Name", "Item Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(menutable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(lbhotelname))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbItemPrice)
                            .addComponent(lbmenuitems))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(menuitemtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itempricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(btaddmenu)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbhotelname)
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbmenuitems)
                            .addComponent(menuitemtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbItemPrice)
                    .addComponent(itempricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(btaddmenu)
                .addContainerGap(198, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btaddmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaddmenuActionPerformed
        System.out.println("res aname "+ restaurantName);
        String menuIt = menuitemtxt.getText();
        Double ip = Double.valueOf(itempricetxt.getText());
        Menu m = new Menu();
        
        m.setItemName(menuIt);
        m.setItemPrice(ip);
        Restaurant ro = system.getRestaurantDirectory().findRestaurant(restaurantName);
        System.out.println("ROOO "+ ro);
        
        if(ro.getMd() == null){
            MenuDirectory md = new MenuDirectory();
            ArrayList<Menu> am  = new ArrayList<>();
            am.add(m);
            md.setMenu(am);
            ro.setMd(md);

            return;
        }
        else{
            MenuDirectory md =   ro.getMd();
            ArrayList<Menu> am  = ro.getMd().getMenu();
            am.add(m);
            md.setMenu(am);
            ro.setMd(md);
        }
        System.out.println("Item"+system.getOrderDirectory().getOrderhist());
        populatetable();
    }//GEN-LAST:event_btaddmenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btaddmenu;
    private javax.swing.JTextField itempricetxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbItemPrice;
    private javax.swing.JLabel lbhotelname;
    private javax.swing.JLabel lbmenuitems;
    private javax.swing.JTextField menuitemtxt;
    private javax.swing.JTable menutable;
    // End of variables declaration//GEN-END:variables
}
