/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdminRole;

import Business.DeliveryMan.DeliveryMan;
import Business.EcoSystem;
import Business.Order.Order;
import Business.Organization;
import Business.Restaurant.Restaurant;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lokesh Balaji
 */
public class ManageOrderpanel extends javax.swing.JPanel {

    /**
     * Creates new form Ordermanagement
     */
      private JPanel userProcessContainer;
    private EcoSystem system;
    private Organization organization;
    private String restaurant;
    private Order orders;
    //private String resName;
    
      String name;
         String address;
         String type ;

    public ManageOrderpanel(JPanel userProcessContainer, EcoSystem system, String restaurant) {
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.restaurant = restaurant;
        initComponents();
        jPanel1.setVisible(false);
        populateOrderList();
        getDeliveryManList();
        populateOrderList();
    }

  
         public void populateOrderList(){
        DefaultTableModel defaultordertable = (DefaultTableModel) manageordertable.getModel();
        defaultordertable.setRowCount(0);
        
        
        System.out.println("Menu "+ system.getRestaurantDirectory().getRestaurantList().size());
        for(Order orders : system.getOrderDirectory().getOrderhist()){
            if(orders.getRestaurant().getName().equals(restaurant)){
            Object row[] = new Object[5];
                row[0] = orders.getOrderID();
                row[1] = orders.getMenuDirectory().getMenu().get(0).getItemName();
               row[2] = orders.getMenuDirectory().getMenu().get(0).getItemPrice();
                row[3] = orders.getMenuDirectory().getMenu().get(0).getQuantity();
                row[4] =  orders;
                defaultordertable.addRow(row);
            }
        }
        
    }
    
         public void getDeliveryManList(){
             for(DeliveryMan dm : system.getDeliveryManDirectory().getDeliveryMan()){
            deliverycombobox.addItem(dm.getDeliveryManName());
        }
        
         }
    
         

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        deliverycombobox = new javax.swing.JComboBox<>();
        btassign = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        manageordertable = new javax.swing.JTable();
        acceptordbt = new javax.swing.JButton();
        vieworderbt = new javax.swing.JButton();
        assigndelbt = new javax.swing.JButton();
        btback = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(240, 137, 38));

        jPanel1.setBackground(new java.awt.Color(240, 137, 38));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("List of Delivery Man Active");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Select Delivery Man");

        deliverycombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Delivery Man" }));

        btassign.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btassign.setText("Assign");
        btassign.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btassign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btassignActionPerformed(evt);
            }
        });

        jSeparator2.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel3)
                        .addGap(86, 86, 86)
                        .addComponent(deliverycombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(btassign)))
                .addContainerGap(118, Short.MAX_VALUE))
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(deliverycombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btassign)
                .addContainerGap(250, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Order Management");

        manageordertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Item Name", "Item Price", "Quantity", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(manageordertable);

        acceptordbt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        acceptordbt.setText("Accept Order");
        acceptordbt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        acceptordbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptordbtActionPerformed(evt);
            }
        });

        vieworderbt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        vieworderbt.setText("View Order");
        vieworderbt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        vieworderbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vieworderbtActionPerformed(evt);
            }
        });

        assigndelbt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        assigndelbt.setText("Assign Deliverymen");
        assigndelbt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        assigndelbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assigndelbtActionPerformed(evt);
            }
        });

        btback.setBackground(new java.awt.Color(204, 204, 204));
        btback.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btback.setText("Back");
        btback.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbackActionPerformed(evt);
            }
        });

        jSeparator1.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btback)
                        .addGap(77, 77, 77)
                        .addComponent(acceptordbt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(vieworderbt)
                        .addGap(67, 67, 67)
                        .addComponent(assigndelbt))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btback)
                    .addComponent(acceptordbt)
                    .addComponent(vieworderbt)
                    .addComponent(assigndelbt))
                .addGap(50, 50, 50)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(316, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void vieworderbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vieworderbtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vieworderbtActionPerformed

    private void btbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btbackActionPerformed

    private void assigndelbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assigndelbtActionPerformed
         int selectedRow = manageordertable.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Please Select a row from table first", "Warining", JOptionPane.WARNING_MESSAGE);
            return;
        }
         orders = (Order)manageordertable.getValueAt(selectedRow,4);
        jPanel1.setVisible(true);
         populateOrderList();
    }//GEN-LAST:event_assigndelbtActionPerformed

    private void acceptordbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptordbtActionPerformed
        int selectedRow = manageordertable.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Please Select a row from table first", "Warining", JOptionPane.WARNING_MESSAGE);
            return;
        }
        orders = (Order)manageordertable.getValueAt(selectedRow,4);
        orders.setOrderStatus("Accepted");
         populateOrderList();
    }//GEN-LAST:event_acceptordbtActionPerformed

    private void btassignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btassignActionPerformed
       // System.out.println("*** "+deliveryCB.getSelectedItem());
       
        DeliveryMan deliveryman = system.getDeliveryManDirectory().findDeliveryMan(String.valueOf(deliverycombobox.getSelectedItem()));
        System.out.println("DDMMMM "+ deliveryman.getDeliveryManName());
        orders.setDeliveryMan(deliveryman);
        JOptionPane.showMessageDialog(null,"Delivery Man Assigned", "Delivery Man Assigned", JOptionPane.INFORMATION_MESSAGE);

        populateOrderList();
    }//GEN-LAST:event_btassignActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptordbt;
    private javax.swing.JButton assigndelbt;
    private javax.swing.JButton btassign;
    private javax.swing.JButton btback;
    private javax.swing.JComboBox<String> deliverycombobox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable manageordertable;
    private javax.swing.JButton vieworderbt;
    // End of variables declaration//GEN-END:variables
}
