/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdminRole;

import Business.EcoSystem;
import Business.Order.Order;
import Business.Organization;
import Business.Restaurant.Restaurant;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lokesh Balaji
 */
public class ManageOrderpanel extends javax.swing.JPanel {

    /**
     * Creates new form Ordermanagement
     */
      private JPanel userProcessContainer;
    private EcoSystem system;
    private Organization organization;
    private String restaurant;
    //private String resName;
    
      String name;
         String address;
         String type ;

    public ManageOrderpanel(JPanel userProcessContainer, EcoSystem system, String restaurant) {
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.restaurant = restaurant;
        initComponents();
        populateOrderList();
    }

  
         public void populateOrderList(){
        DefaultTableModel defaultordertable = (DefaultTableModel) manageordertable.getModel();
        defaultordertable.setRowCount(0);
        
        
        System.out.println("Menu "+ system.getRestaurantDirectory().getRestaurantList().size());
        for(Order orders : system.getOrderDirectory().getOrderhist()){
            if(orders.getRestaurant().getName().equals(restaurant)){
            Object row[] = new Object[5];
                row[0] = orders.getOrderID();
                row[1] = orders.getMenuDirectory().getMenu().get(0).getItemName();
//                row[2] = order.getMenuDirectory().getMenu().get(0).getItemPrice();
//                row[3] = order.getMenuDirectory().getMenu().get(0).getQuantity();
                row[4] =  orders.getOrderStatus();
                defaultordertable.addRow(row);
            }
        }
        
    }
   
    
         

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        manageordertable = new javax.swing.JTable();
        acceptordbt = new javax.swing.JButton();
        vieworderbt = new javax.swing.JButton();
        assigndelbt = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Order Management");

        manageordertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Item Name", "Item Price", "Quantity", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(manageordertable);

        acceptordbt.setText("Accept Order");

        vieworderbt.setText("View Order");
        vieworderbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vieworderbtActionPerformed(evt);
            }
        });

        assigndelbt.setText("Assign Deliverymen");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(acceptordbt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(vieworderbt)
                        .addGap(80, 80, 80)
                        .addComponent(assigndelbt))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acceptordbt)
                    .addComponent(vieworderbt)
                    .addComponent(assigndelbt))
                .addContainerGap(462, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void vieworderbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vieworderbtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vieworderbtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptordbt;
    private javax.swing.JButton assigndelbt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable manageordertable;
    private javax.swing.JButton vieworderbt;
    // End of variables declaration//GEN-END:variables
}
