/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Organization;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Lokesh Balaji
 */
public class ManageDeliverymenpanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageDeliverymenpanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    private Organization delorganizat;

    public ManageDeliverymenpanel(JPanel userProcessContainer, EcoSystem system, Organization delorganizat) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.delorganizat = delorganizat;
    }

   
            
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btdeldelivery = new javax.swing.JButton();
        btcreatedel = new javax.swing.JButton();
        titlemandel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablemandel = new javax.swing.JTable();
        btback = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btdeldelivery.setText("Delete Delivery man");
        add(btdeldelivery, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 226, -1, -1));

        btcreatedel.setText("Create Deliverymen");
        btcreatedel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcreatedelActionPerformed(evt);
            }
        });
        add(btcreatedel, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 226, -1, -1));

        titlemandel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titlemandel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlemandel.setText("Manage Delivery Man");
        add(titlemandel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 13, 651, 42));

        tablemandel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Username"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablemandel);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 102, -1, 95));

        btback.setText("Back");
        btback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbackActionPerformed(evt);
            }
        });
        add(btback, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 226, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btbackActionPerformed

    private void btcreatedelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcreatedelActionPerformed
         NewDeliverymenPanel createdel = new NewDeliverymenPanel(userProcessContainer, system, delorganizat);
        userProcessContainer.add("NewCustomerPanel", createdel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btcreatedelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btback;
    private javax.swing.JButton btcreatedel;
    private javax.swing.JButton btdeldelivery;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablemandel;
    private javax.swing.JLabel titlemandel;
    // End of variables declaration//GEN-END:variables
}
