/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Organization;
import Business.Role.CustomerRole;
import Business.Role.DeliverManRole;
import java.awt.CardLayout;
import java.awt.Component;
import javafx.scene.paint.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Lokesh Balaji
 */
public class NewCustomerPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageCustomerPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    private Organization custorganization;

    /**
     * Creates new form CreateNewCustomerJPanel
     */
    public NewCustomerPanel(JPanel userProcessContainer,EcoSystem system,Organization custorganization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system=system;
        this.custorganization=custorganization;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btback = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbtitlec = new javax.swing.JLabel();
        lbname = new javax.swing.JLabel();
        lbusername = new javax.swing.JLabel();
        lbpassword = new javax.swing.JLabel();
        txtcusname = new javax.swing.JTextField();
        txtcususername = new javax.swing.JTextField();
        txtcuspassword = new javax.swing.JTextField();
        btsave = new javax.swing.JButton();
        emaillb = new javax.swing.JLabel();
        txtcusemailid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        btback.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btback.setText("Back");
        btback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbackActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        lbtitlec.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbtitlec.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbtitlec.setText("Create New Customer");

        lbname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbname.setText("Name:");

        lbusername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbusername.setText("Username:");

        lbpassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbpassword.setText("Password:");

        txtcuspassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcuspasswordActionPerformed(evt);
            }
        });

        btsave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btsave.setText("Save");
        btsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsaveActionPerformed(evt);
            }
        });

        emaillb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        emaillb.setText("Email ID:");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbtitlec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbusername)
                    .addComponent(lbname)
                    .addComponent(lbpassword)
                    .addComponent(emaillb)
                    .addComponent(jButton1))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtcusname)
                        .addComponent(txtcususername)
                        .addComponent(txtcuspassword)
                        .addComponent(txtcusemailid, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                    .addComponent(btsave, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbtitlec, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbname)
                    .addComponent(txtcusname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbusername)
                    .addComponent(txtcususername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbpassword)
                    .addComponent(txtcuspassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emaillb)
                    .addComponent(txtcusemailid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btsave)
                    .addComponent(jButton1))
                .addContainerGap(112, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtcuspasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcuspasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcuspasswordActionPerformed

    private void btsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsaveActionPerformed
        String customername = txtcusname.getText();
        String customerusername = txtcususername.getText();
        String customerpassword = txtcuspassword.getText();
        String customeremailid = txtcusemailid.getText();
        
        Employee emp = system.getEmployeeDirectory().createEmployee(customername);
        system.getUserAccountDirectory().createUserAccount(customerusername, customerpassword, emp, new CustomerRole());
        Business.Customer.Customer customer = (Business.Customer.Customer) system.getCustomerDirectory().createOrganization(Organization.Type.Customer);
        customer.setName("Customer");
        Business.Role.CustomerRole customerrole = new CustomerRole();
        customer.getUserAccountDirectory().createUserAccount(customername, customerpassword, emp, customerrole);
        JOptionPane.showMessageDialog(null, "Customer Saved Successfully");
        
       
       
    }//GEN-LAST:event_btsaveActionPerformed

    private void btbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbackActionPerformed
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        layout.previous(userProcessContainer);
        Component[] comps = this.userProcessContainer.getComponents();
        for(Component comp : comps){
            if(comp instanceof ManageCustomerPanel){
                ManageCustomerPanel manageCustomersJPanel= (ManageCustomerPanel) comp;
               manageCustomersJPanel.populatetable(); 
            }
        }
    }//GEN-LAST:event_btbackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        layout.previous(userProcessContainer);
        Component[] comps = this.userProcessContainer.getComponents();
        for(Component comp : comps){
            if(comp instanceof ManageCustomerPanel){
                ManageCustomerPanel manageCustomersJPanel= (ManageCustomerPanel) comp;
               manageCustomersJPanel.populatetable(); 
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btback;
    private javax.swing.JButton btsave;
    private javax.swing.JLabel emaillb;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbname;
    private javax.swing.JLabel lbpassword;
    private javax.swing.JLabel lbtitlec;
    private javax.swing.JLabel lbusername;
    private javax.swing.JTextField txtcusemailid;
    private javax.swing.JTextField txtcusname;
    private javax.swing.JTextField txtcuspassword;
    private javax.swing.JTextField txtcususername;
    // End of variables declaration//GEN-END:variables
}
