/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.DeliveryMan.DeliveryMan;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Organization;
import Business.Restaurant.Restaurant;
import Business.Role.CustomerRole;
import Business.Role.DeliverManRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Lokesh Balaji
 */
public class NewDeliverymenPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewDeliverymenPanel
     */
       private JPanel userProcessContainer;
    private EcoSystem system;
    private Organization organization;
    private Restaurant restaurant;
      String name;
      String username;
         String address;
         String type ;

    public NewDeliverymenPanel(JPanel userProcessContainer, EcoSystem system) {
       initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
    }
         

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbtitlenewdel = new javax.swing.JLabel();
        lbname = new javax.swing.JLabel();
        lbusername = new javax.swing.JLabel();
        lbpassword = new javax.swing.JLabel();
        txtdelname = new javax.swing.JTextField();
        txtdelusername = new javax.swing.JTextField();
        txtdelpassword = new javax.swing.JTextField();
        lbphoneno = new javax.swing.JLabel();
        txtdelphoneno = new javax.swing.JTextField();
        btback = new javax.swing.JButton();
        btsave = new javax.swing.JButton();

        setBackground(new java.awt.Color(240, 147, 38));

        lbtitlenewdel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbtitlenewdel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbtitlenewdel.setText("Create New Delivery Man");

        lbname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbname.setText("Name:");

        lbusername.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbusername.setText("Username:");

        lbpassword.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbpassword.setText("Password:");

        txtdelname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdelnameActionPerformed(evt);
            }
        });

        lbphoneno.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbphoneno.setText("Phone no:");

        btback.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btback.setText("Back");
        btback.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbackActionPerformed(evt);
            }
        });

        btsave.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btsave.setText("Save");
        btsave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbtitlenewdel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btback)
                    .addComponent(lbphoneno))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtdelphoneno, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btsave))
                .addContainerGap(170, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbname)
                    .addComponent(lbusername)
                    .addComponent(lbpassword))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtdelname, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdelusername, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdelpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbtitlenewdel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbname)
                    .addComponent(txtdelname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbusername)
                    .addComponent(txtdelusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbpassword)
                    .addComponent(txtdelpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbphoneno)
                    .addComponent(txtdelphoneno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btback)
                    .addComponent(btsave))
                .addContainerGap(203, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtdelnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdelnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdelnameActionPerformed

    private void btsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsaveActionPerformed
        String name = txtdelname.getText();
        //String add = dName.getText();
        String username = txtdelusername.getText();
        String password = txtdelpassword.getText();
        if(name.isEmpty() || username.isEmpty() || password.isEmpty()){
           JOptionPane.showMessageDialog(null,"All the fields are required", "Success", JOptionPane.ERROR_MESSAGE);
           return;
        }
        
        Employee emp = system.getEmployeeDirectory().createEmployee(name);
        UserAccount account = system.getUserAccountDirectory().createUserAccount(username, password, emp, new DeliverManRole());
        system.getDeliveryManDirectory().createDeliveryMan(name,username);
         
        
        JOptionPane.showMessageDialog(null, "Delivery Man Saved Successfully");
    }//GEN-LAST:event_btsaveActionPerformed

    private void btbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbackActionPerformed
      userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
        Component[] comps = this.userProcessContainer.getComponents();
        for(Component comp : comps){
            if(comp instanceof SystemAdminWorkAreaJPanel){
                SystemAdminWorkAreaJPanel systemAdminWorkAreaJPanel= (SystemAdminWorkAreaJPanel) comp;
               systemAdminWorkAreaJPanel.populateTree(); 
            }
        }
    }//GEN-LAST:event_btbackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btback;
    private javax.swing.JButton btsave;
    private javax.swing.JLabel lbname;
    private javax.swing.JLabel lbpassword;
    private javax.swing.JLabel lbphoneno;
    private javax.swing.JLabel lbtitlenewdel;
    private javax.swing.JLabel lbusername;
    private javax.swing.JTextField txtdelname;
    private javax.swing.JTextField txtdelpassword;
    private javax.swing.JTextField txtdelphoneno;
    private javax.swing.JTextField txtdelusername;
    // End of variables declaration//GEN-END:variables
}
