/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.List;
import javax.swing.JPanel;

/**
 *
 * @author Lokesh Balaji
 */
public class ViewCustomerPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewCustomerPanel
     */
     private JPanel userProcessContainer;
    private EcoSystem system;
    private Organization custorganization;
    private UserAccount useracc;
    private Employee employee;

    public ViewCustomerPanel(JPanel userProcessContainer, EcoSystem system, Organization custorganization, UserAccount useracc, Employee employee) {
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.custorganization = custorganization;
        this.useracc= useracc;
        this.employee=employee;
        initComponents();
        cusvnametxt.setText(employee.getName());
        cusvusernametxt.setText(useracc.getUsername());
        cusvpasswordtxt.setText(useracc.getPassword());
        //cusvemailtxt.setText(useracc.get);
    }
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbname = new javax.swing.JLabel();
        lbcusvpassword = new javax.swing.JLabel();
        lbcusvusername = new javax.swing.JLabel();
        lbcusvemailid = new javax.swing.JLabel();
        cusvnametxt = new javax.swing.JTextField();
        cusvpasswordtxt = new javax.swing.JTextField();
        cusvusernametxt = new javax.swing.JTextField();
        cusvemailtxt = new javax.swing.JTextField();
        btsave = new javax.swing.JButton();
        btback = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Customer");

        lbname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbname.setText("Name:");

        lbcusvpassword.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbcusvpassword.setText("Password:");

        lbcusvusername.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbcusvusername.setText("Username:");

        lbcusvemailid.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbcusvemailid.setText("Email ID:");

        cusvusernametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusvusernametxtActionPerformed(evt);
            }
        });

        btsave.setText("Save");
        btsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsaveActionPerformed(evt);
            }
        });

        btback.setText("Back");
        btback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbname)
                    .addComponent(lbcusvpassword)
                    .addComponent(lbcusvusername)
                    .addComponent(lbcusvemailid))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btback)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btsave))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cusvusernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cusvnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cusvpasswordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cusvemailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbname)
                    .addComponent(cusvnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbcusvusername)
                    .addComponent(cusvusernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbcusvpassword)
                    .addComponent(cusvpasswordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbcusvemailid)
                    .addComponent(cusvemailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btsave)
                    .addComponent(btback))
                .addContainerGap(104, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cusvusernametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusvusernametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cusvusernametxtActionPerformed

    private void btbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbackActionPerformed
       CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        layout.previous(userProcessContainer);
        Component[] comps = this.userProcessContainer.getComponents();
        for(Component comp : comps){
            if(comp instanceof ManageCustomerPanel){
                ManageCustomerPanel manageCustomersJPanel= (ManageCustomerPanel) comp;
               manageCustomersJPanel.populatetable(); 
            }
        }
    }//GEN-LAST:event_btbackActionPerformed

    private void btsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsaveActionPerformed
        String name = cusvnametxt.getText();
         String username = cusvusernametxt.getText();
         String password = cusvpasswordtxt.getText();
         String emailid = cusvemailtxt.getText();
      List<Organization> organizationcus =system.getCustomerDirectory().searchOrganization("Customer") ;
      for(Organization org : organizationcus){
        for(UserAccount u:org.getUserAccountDirectory().getUserAccountList()) {
                u.setUsername(username);
                u.setPassword(password);
            }
    }
    }//GEN-LAST:event_btsaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btback;
    private javax.swing.JButton btsave;
    private javax.swing.JTextField cusvemailtxt;
    private javax.swing.JTextField cusvnametxt;
    private javax.swing.JTextField cusvpasswordtxt;
    private javax.swing.JTextField cusvusernametxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbcusvemailid;
    private javax.swing.JLabel lbcusvpassword;
    private javax.swing.JLabel lbcusvusername;
    private javax.swing.JLabel lbname;
    // End of variables declaration//GEN-END:variables
}
